version: '3.6'

services:
  website:
    image: palestinenights/website
    restart: on-failure
    depends_on:
      - proxy
      - places
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: palestinenights.com, www.palestinenights.com;'
      traefik.port: 80

  places:
    image: ashanaakh/places
    restart: on-failure
    depends_on:
      - proxy
    env_file:
     - ./config/places.env
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: places.palestinenights.com;'
      traefik.port: 8080

  redis:
    image: redis
    restart: on-failure
    volumes:
       - redis-data:/data

  proxy:
    image: traefik
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/acme.json:/acme.json
      - ./config/traefik.toml:/etc/traefik/traefik.toml:ro
    networks:
      default:
        aliases:
          - www.palestinenights.com
          - palestinenights.com
          - dashboard.palestinenights.com
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: dashboard.palestinenights.com'
      traefik.port: 8080

volumes:
  redis-data: