version: '3.6'

services:
  website:
    image: palestinenights/website
    restart: always
    depends_on:
      - proxy
      - places
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: palestinenights.com, www.palestinenights.com;'
      traefik.port: 80

  places:
    image: ashanaakh/places
    restart: always
    depends_on:
      - proxy
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: places.palestinenights.com;'
      traefik.port: 8000

  proxy:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./config/acme.json:/acme.json
    networks:
      default:
        aliases:
          - www.palestinenights.com
          - palestinenights.com
          - dashboard.palestinenights.com
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: dashboard.palestinenights.com'
      traefik.port: 8080
